### PR TITLE
Add vCard link to homepage

### PR DESCRIPTION
**Pull request by imacrayon**
Fixes issue #7. This imports into Apple Contacts just fine, but might need to be tested on other platforms. According to this [Wikipedia article](https://en.wikipedia.org/wiki/VCard) `FN` is a required field. I've added `ORG` so that the contact info is treated as an organization instead of a person.

### CODE REVIEW

**Comment by sethetter** [comment]
@imacrayon trying to import this on Android gave me an error: "This format is not supported". Digging around a bit now.

**Comment by sethetter** [comment]
@imacrayon I exported a contact on my android phone and inspected it and it was using version 2.1. Dropping down to that version made things work. Give that a shot and make sure it still works on iOS and we'll be good to go!

**Comment by imacrayon** [comment]
@sethetter ok - so version 2.1 works in Apple Contacts - but now that I'm testing on iOS, mobile Safari doesn't automatically import .vcf files for some reason. You have to either text or email the file to yourself first before you can import it and that's not very intuitive. Would it make sense to turn this link into a little form where you can input your phone number and it'll text you a vCard?

What's odd is that [this SO question](https://stackoverflow.com/questions/1892373/iphone-how-to-get-safari-to-recognize-a-vcard) claims that importing vCards is supported since iOS7, but so far I can only get the browswer to prompt me to save it to iCloud without actually importing it into Contacts.

**Comment by sethetter** [comment]
@imacrayon om Android it doesn't auto import on download either, but the download notification let's me open it directly after it's downloaded, then that kicks off the import.

I wonder if the `tel:` link is more user friendly? The only difference is they enter all the other information themselves. What do you think?

**Comment by imacrayon** [comment]
@sethetter that's a bummer, yeah I'm thinking that sticking with the `:tel` link might be the way to go. I feel like people have a pretty good idea how to add a contact through their messaging app, but the vCard process is really convoluted especially on iOS. Even after opening the file on my iPhone I don't get an option to import it 😕

**Comment by sethetter** [comment]
Let's keep the route and view around and just keep the link as the tel link for now. Maybe we can just have it as a smaller link below for those who prefer it?

**Pull request merged**
